# Generated by Django 4.2.7 on 2025-10-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='diaryentry',
            unique_together=set(),
        ),
    ]
